#include <qapplication.h>
#include <qpushbutton.h>
#include <qmainwindow.h>
#include <qdesktopwidget.h>
#include <QHBoxLayout>
#include <QPixmap>
#include <QImage>
#include <QMouseEvent>
#include <QPalette>
#include <QDebug>
#include <QGraphicsProxyWidget>
#include <QWidget>
#include <fstream>
#include <qgraphicsitemanimation.h>
#include <qgraphicsitem.h>
#include <qgraphicsscene.h>
#include <qgraphicsview.h>
#include <QGraphicsPixmapItem>
#include <QGraphicsSceneMouseEvent>
#include <QTransform>
#include <string>
#include <qlineedit.h>
#include <QToolBar>
#include <QToolButton>
#include <QVector>