#include <qapplication.h>
#include <qpushbutton.h>
#include <qmainwindow.h>
#include <qdesktopwidget.h>
#include <QHBoxLayout>
#include <QPixmap>
#include <QImage>
#include <QMouseEvent>
#include <QPalette>
#include <QDebug>
